sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="master"
matrix:
  include:
    - python: "2.7"
      env: DJANGO="1.11"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.0"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.1"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="master"
  allow_failures:
    - python: "3.4"
      env: DJANGO="2.0"
    - python: "3.4"
      env: DJANGO="master"
    - python: "3.5"
      env: DJANGO="2.0"
    - python: "3.5"
      env: DJANGO="master"
    - python: "3.6"
      env: DJANGO="2.0"
    - python: "3.6"
      env: DJANGO="master"
after_success: codecov
install: pip install tox-travis codecov
script: tox
